config/routes.rb
MoviesCucumbers::Application.routes.draw do
	root :to => 'home#index'
	devise_for :users

	resources :recommendations, only: [:index] 
	resources :ratings, only: [:index, :create, :update]

	get '/search' => 'ratings#search', as: 'search'

	get '/users/ratings' => 'users#ratings', as: 'user_ratings'

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  attr_accessible :name
  has_many :actors_movies, dependent: :destroy
  has_many :movies, through: :actors_movies

  validates :name, presence: true

  posify do
    # The searchable content.
    [self.name].join ' '
  end

end

app/models/actor_movie.rb
class ActorMovie < ActiveRecord::Base

  attr_accessible :actor_id, :movie_id
  belongs_to :actor
  belongs_to :movie
  
end

app/models/actors_movie.rb
class ActorsMovie < ActiveRecord::Base

  attr_accessible :actor_id, :movie_id
  belongs_to :actor
  belongs_to :movie
  
end

app/models/director.rb
class Director < ActiveRecord::Base

  attr_accessible :name
  has_many :directors_movies, dependent: :destroy
  has_many :movies, through: :directors_movies

  validates :name, presence: true

  posify do
    # The searchable content.
    [self.name].join ' '
  end

end

app/models/directors_movie.rb
class DirectorsMovie < ActiveRecord::Base
  
  attr_accessible :movie_id, :director_id
  belongs_to :movie
  belongs_to :director

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  attr_accessible :name
  has_many :genres_movies, dependent: :destroy
  has_many :movies, through: :genres_movies

  validates :name, presence: true
  
end

app/models/genre_movie.rb
class GenreMovie < ActiveRecord::Base

  attr_accessible :movie_id, :genre_id
  belongs_to :movie
  belongs_to :genre
  
end

app/models/genres_movie.rb
class GenresMovie < ActiveRecord::Base

  attr_accessible :movie_id, :genre_id
  belongs_to :movie
  belongs_to :genre
  
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  attr_accessible :title, :rt_id, :tmdb_id, :director_id,
  :critic_consensus, :rt_score, :poster_url, :trailer_url, 
  :mpaa_rating, :run_time, :imdb_ref, :tmdb_rating, :release_date,
  :budget, :demo_display

  has_many :ratings, dependent: :destroy 
  has_many :users, through: :ratings

  has_many :actors_movies, dependent: :destroy
  has_many :actors, through: :actors_movies

  has_many :genres_movies, dependent: :destroy
  has_many :genres, through: :genres_movies

  has_many :directors_movies, dependent: :destroy
  has_many :directors, through: :directors_movies

  has_many :recommendations, dependent: :destroy
  has_many :users, through: :recommendations

  posify do
    # The searchable content.
    [self.title].join ' '
  end
  
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  attr_accessible :movie_id, :user_id, :viewable, :rating_value
  belongs_to :movie
  belongs_to :user

  validates_uniqueness_of :user_id, :scope => [:movie_id]
  validates :movie_id, :user_id, :rating_value, presence: true

  validates :rating_value, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5}
  
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  attr_accessible :movie_id, :user_id

  belongs_to :user
  belongs_to :movie

  validates_uniqueness_of :user_id, :scope => [:movie_id]
  validates :user_id, :movie_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  include ContentHelper
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :ratings, dependent: :destroy
  has_many :movies, through: :ratings

  has_many :recommendations, dependent: :destroy
  has_many :movies, through: :recommendations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def get_fifty
    # movies = []
    # until movies.length == 52 
    #   random_number = Random.rand(1..Movie.count)
    #   movie = Movie.where(:id => random_number).first
    #   if !movie.nil?
    #     movies << movie unless movies.include? movie
    #   end 
    # end
    # remove_duplicates(movies)
    # movies
    Movie.where(:demo_display => true).sample(52)
  end

  def remove_duplicates(movies)
    movies.delete_if do |movie|
      Rating.where(user_id: current_user.id).pluck(:movie_id).include? movie.id
    end
    movies
  end

  def get_ratings!
    @ratings = current_user.ratings
    @ratings_movie_ids = @ratings.pluck(:movie_id)
    @rating_values = {}
    current_user.ratings.each do |rating|
      @rating_values[rating.movie_id] = rating.rating_value 
    end
  end

  def get_upcoming_movies
   upcoming_movies = HTTParty.get('http://api.rottentomatoes.com/api/public/v1.0/lists/movies/upcoming.json?apikey='+ RT_API_KEY )
   @prepopulated_upcoming_movies = upcoming_movies['movies']
      @prepopulated_upcoming_movies.each do |attr|
        bad_dates = attr['release_dates']['theater'].split('-').map{|d|d.to_i}
        ok_dates = Date.new(bad_dates[0],bad_dates[1],bad_dates[2])
        attr['release_dates']['theater'] = ok_dates.to_formatted_s(:long_ordinal)
      end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to recommendations_path
    # else
  		# get_upcoming_movies
  	end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_ratings!
  
  def index
    @movies = get_fifty
  end

  def create
    params[:rating_value] = params[:rating_value].to_i
    params[:movie_id] = params[:movie_id].to_i
    rating = Rating.new(rating_value: params[:rating_value], movie_id: params[:movie_id], user_id: current_user.id)

    if rating.save
      UpdateRecsWorker.perform_async(params[:movie_id], params[:rating_value], current_user.id)
      render json: rating
    else
      render json: rating.errors
    end
  end


  def update
    rating = Rating.find(params[:id])
    rating.rating_value = params[:rating_value]

    if rating.save
      UpdateRecsWorker.perform_async(params[:movie_id], params[:rating_value], current_user.id)
      render json: rating 
    else
      flash[:notice] = "Your ratings did not update."
      render json: rating.errors 
    end
    
  end

  def search
    result = Pose.search "#{params[:query]}", [Movie, Actor, Director], limit: 20
    query_match = params[:query].downcase
    result[Actor].each do |actor|
      if actor.name.downcase == query_match
        @actor_movies = actor.movies
      end
    end

    result[Director].each do |director|
      if director.name.downcase == query_match
        @director_movies = director.movies
      end
    end

    @movies = result[Movie]
  end
end   

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_ratings!

  def index
    @recommendations = current_user.recommendations
    @recommendations.delete_if do |rec|
      current_user.ratings.pluck(:movie_id).include? rec.movie_id
    end
    @recommendations.shuffle!
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_ratings!

  def ratings
    @ratings = current_user.ratings.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
  
end

app/helpers/content_helper.rb
module ContentHelper
end

app/views/home/index.html.erb
<div class='login-background'>

<div class="front-form">

	<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name, :id => 'fron-login')) do |f| %>

	<div class="errors">
  	<%= devise_error_messages! %></div>

  <div class="email">
  <%= f.email_field :email %></div>

  <div class="password">
  <%= f.password_field :password %></div>

  <div class="password-confirm">
  <%= f.password_field :password_confirmation %></div>

  <div class="sign-up"><%= f.submit "Sign up", class: "pure-button pure-button-primary"%></div>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<div class='lower'>

	<div class='lower-box'>
		<div class="column-1">
				<div class='column-1-title'>
					Hire Us!
				</div>
				<div class='github'><br>
				<a href='http://www.github.com/seaseng'>Navid Mostafavi</a><br>
				<a href='http://www.github.com/mcarthurgill'>McArthur Gill</a><br>
				<a href='http://www.github.com/rowlandyj'>Rowland Jiao</a><br>
				<a href='http://www.github.com/byee322'>Brian Yee</a>
			</div>
		</div>

	<div class="column-2">
		<%= image_tag("paramount-logo.png", id: "stars") %>
		<div id="logo">
			<%= image_tag("mascot.png", height:'200', width: '120') %>
		</div>
	</div>

	<div class="column-3">
		<div class='copyright'>
			<br>
			<br>
			<br>
			<br>
			A <a href="http://www.devbootcamp.com">DevBootCamp</a> Original
		</div>
		<div class ='devbootcamp'>
			<%= image_tag 'devbootcamp.png' %>
		</div>
	</div>

</div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to(image_tag('mnclogo.png', height: '300', width: '340', id: 'brand'), root_path) %>
<ul class="nav">
  <% if user_signed_in? %>
   <li>
     <%= link_to recommendations_path, id: 'recommendation' do %><i class="icon-film"></i> Recommendations
     <% end %>
   </li>
   <li>
    <%= link_to ratings_path, id: 'rate' do %><i class="icon-thumbs-up-alt"></i> Rate Movies
    <% end %>
  </li>
  <li>
    <%= link_to user_ratings_path do %><i class="icon-archive"></i> My Ratings
    <% end %>
  </li>
  <li>
    <%= link_to edit_user_registration_path do %><i class="icon-user"></i> My Account
    <% end %>
  </li>
  <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
  </li>
  <% else %>
    <li>
      <%= link_to 'Sign up', new_user_registration_path %>
    </li>
    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_search-bar.html.erb
<% if user_signed_in? %>
	<div id="search">
	  <%= form_tag("/search", method: "get", :class => 'pure-form pure-g') do %>
	    <%= text_field_tag :query, nil, :class => 'pure-input-1-2', :placeholder => 'Search for keywords' %>
	    <button class="pure-button pure-button-primary"><i class="icon-search"></i> Search</button>
	  <% end %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Movies Cucumbers" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Movies&Cucumbers" %>">
  <link href='http://fonts.googleapis.com/css?family=Hanuman:400,700' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>

<body class="<%= controller_name %> <%= action_name %>">
  <div class="row-fluid">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
         <%= render 'layouts/navigation' %>
       </div>
     </nav>
   </div>
    <%= render 'layouts/search-bar' %>
    <div id="main" role="main">
      <div class="container">
        <div class="span12">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div> <!--! end of container -->
    </div> <!--! end of #main -->
            <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/ratings/index.html.erb
<div class='movie-list'>
  <% @movies.each do |movie| %>
    <% rated_movie =  @ratings.include? movie.id  %>
    <% current_rating = @rating_values[movie.id].to_i %>
    <% if rated_movie %>
      <% rating = Rating.where(movie_id: movie.id, user_id: current_user.id).first %>
      <%= render 'shared/movie', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating, :rating => rating %>
    <% else %>
      <%= render 'shared/movie_no_rating', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating%>
    <% end %> 
  <% end %>
</div>

app/views/ratings/search.html.erb
<div class='movie-list'>
  <% if @actor_movies.nil? && @director_movies.nil? && @movies.nil? %>
    <p>Nothing matched your search.</p>
  <% elsif @actor_movies %>
    <% @actor_movies.each do |movie| %>
      <% rated_movie =  @ratings_movie_ids.include? movie.id %>
      <% current_rating = @rating_values[movie.id].to_i %>
      <% if rated_movie %>
        <% rating = Rating.where(movie_id: movie.id, user_id: current_user.id).first %>
        <%= render 'shared/movie', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating, :rating => rating %>
      <% else %>
        <%= render 'shared/movie_no_rating', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating %>
      <% end %>
    <% end %>
  <% elsif @director_movies %>
    <% @director_movies.each do |movie| %>
      <% rated_movie =  @ratings_movie_ids.include? movie.id %>
      <% current_rating = @rating_values[movie.id].to_i %>
      <% if rated_movie %>
        <% rating = Rating.where(movie_id: movie.id, user_id: current_user.id).first %>
        <%= render 'shared/movie', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating, :rating => rating %>
      <% else %>
        <%= render 'shared/movie_no_rating', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating %>
      <% end %>
    <% end %>
  <% else %>
    <% @movies.each do |movie| %>
      <% rated_movie =  @ratings_movie_ids.include? movie.id %>
      <% current_rating = @rating_values[movie.id].to_i %>
      <% if rated_movie %>
        <% rating = Rating.where(movie_id: movie.id, user_id: current_user.id).first %>
        <%= render 'shared/movie', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating, :rating => rating %>
      <% else %>
        <%= render 'shared/movie_no_rating', :movie => movie, :rated_movie => rated_movie, :current_rating => current_rating %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/recommendations/index.html.erb
<div class='movie-list'>
  <% if @recommendations.empty? %>
    <h2><%= link_to "Please rate more movies to receive recommendations!", ratings_path %></h2>
  <% else %>
    <% @recommendations.each do |recommendation| %>
      <% rated_movie =  @ratings.include? recommendation.movie_id  %>
      <% current_rating = @rating_values[recommendation.movie_id].to_i %>
        <%= render 'shared/movie_no_rating', :movie => recommendation.movie, :rated_movie => rated_movie, :current_rating => current_rating %>
    <% end %>
  <% end %>

</div>

app/views/shared/_movie.html.erb
<div class="ratings-movie">
  <div class='poster'>
    <%= link_to(image_tag(movie.poster_url, height: '300'), movie.trailer_url) %>
  </div>

  <div class='title'>
    <%= link_to(movie.title, movie.trailer_url) %>
  </div>

  <span class='date'>
     (<%= movie.release_date.year %>)  
  </span>

  <span class='mpaa-rating'>
    <% if movie.mpaa_rating.nil? || movie.mpaa_rating.empty? %>
      Not Rated
    <% else %>
      <%= movie.mpaa_rating %>        
    <% end %>
  </span>

  <div class="rating" data-current_rating="<%= current_rating if current_rating%>">
    <%= link_to '☆', rating_path(rating, rating_value: 1, movie_id: movie.id),  :method => :put, remote: true, class: "movie-rating-value", 'data-movie_id' => movie.id, 'data-rating_value' => 1, 'data-rating_id' => rating.id %>
    <%= link_to '☆', rating_path(rating, rating_value: 2, movie_id: movie.id),  :method => :put, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 2, 'data-rating_id' => rating.id%>
    <%= link_to '☆', rating_path(rating, rating_value: 3, movie_id: movie.id),  :method => :put, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 3, 'data-rating_id' => rating.id%>
    <%= link_to '☆', rating_path(rating, rating_value: 4, movie_id: movie.id),  :method => :put, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 4, 'data-rating_id' => rating.id%>
    <%= link_to '☆', rating_path(rating, rating_value: 5, movie_id: movie.id),  :method => :put, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 5, 'data-rating_id' => rating.id%>
  </div>


</div>

app/views/shared/_movie_no_rating.html.erb
<div class="ratings-movie">
  <div class='poster'>
    <%= link_to(image_tag(movie.poster_url, height: '300'), movie.trailer_url) %>
  </div>

  <div class='title'>
    <%= link_to(movie.title, movie.trailer_url) %>
  </div>

  <span class='date'>
     (<%= movie.release_date.year %>)  
  </span>

  <span class='mpaa-rating'>
    <% if movie.mpaa_rating.nil? || movie.mpaa_rating.empty? %>
      Not Rated
    <% else %>
      <%= movie.mpaa_rating %>        
    <% end %>
  </span>

  <div class="rating" data-current_rating="<%= current_rating if current_rating%>">
    <%= link_to '☆', ratings_path(rating_value: 1, movie_id: movie.id),  :method => :post, remote: true, class: "movie-rating-value", 'data-movie_id' => movie.id, 'data-rating_value' => 1%>
    <%= link_to '☆', ratings_path(rating_value: 2, movie_id: movie.id),  :method => :post, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 2%>
    <%= link_to '☆', ratings_path(rating_value: 3, movie_id: movie.id),  :method => :post, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 3%>
    <%= link_to '☆', ratings_path(rating_value: 4, movie_id: movie.id),  :method => :post, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 4%>
    <%= link_to '☆', ratings_path(rating_value: 5, movie_id: movie.id),  :method => :post, remote: true, class: "movie-rating-value",  'data-movie_id' => movie.id, 'data-rating_value' => 5%>
  </div>

</div>

app/views/shared/_upcoming_movies.html.erb
<% @prepopulated_upcoming_movies.each do |upcoming| %>
    <div class="movie">

      <div class="clips_url" style="display: none">
        <%= upcoming['links']['clips']%>
      </div>

      <div class='poster'>
      <%= image_tag(upcoming['posters']['detailed'], height: "250") %>
      </div>

      <div class="title">
        <%= upcoming['title']%>
      </div>

      <div class="release_date">
        <%= upcoming['release_dates']['theater'] %>
      </div>

      <div class="tomatoes">
        <% if upcoming['ratings']['critics_rating'] == 'Fresh' %>
          <%= image_tag '/assets/tomatoe-icons.png',{height:15}%>
        <% elsif upcoming['ratings']['critics_rating'] == 'Rotten'%>
          <%= image_tag '/assets/rotten.gif',{height:15}%>
        <% else %>
        <% end %>
        <span class="critics_rating"> 
          <%= upcoming['ratings']['critics_rating'] %>
        </span>

        <% if upcoming['ratings']['critics_score'] < 65 %>
          <i class="icon-thumbs-down-alt"></i>
        <% elsif upcoming['ratings']['critics_score'] >= 65 && upcoming['ratings']['critics_score'] <= 75 %>
          <i class="icon-meh"></i>
        <% else %>
          <i class="icon-thumbs-up-alt"></i>
        <% end %>
        <span class="critics_score">
          <%= upcoming['ratings']['critics_score'] %>
        </span>%
        <span class="audience_score">
          <i class="icon-male"></i>
        <%= upcoming['ratings']['audience_score'] %>
          </span>%
      </div>

    </div>

  <% end %>

app/views/users/ratings.html.erb
<div class='movie-list'>
  <% @ratings.each do |rating| %>
    <% rated_movie =  true %>
    <% current_rating = @rating_values[rating.movie_id].to_i %>
    <%= render 'shared/movie', :movie => rating.movie, :rated_movie => rated_movie, :current_rating => current_rating, :rating => rating%>
  <% end %>
</div>